name: cheqd-node CI

on: 
  push:
    paths-ignore:
    - '**.md'
    - 'docs/**'
    - 'architecture/**'

env:
  NODE_CONFIGS_BASE: "~/work/cheqd-node/cheqd-node/test/networks/docker_compose/node_configs"

jobs:
  # lint:
  #   name: cheqd-node linting
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: golangci-lint
  #       uses: golangci/golangci-lint-action@v2
  #       with:
  #         version: v1.40
  #         args: --timeout 5m0s

  # test:
  #   name: cheqd-node unit tests
  #   runs-on: ubuntu-latest
  #   needs: lint
  #   steps:
  #     - name: Set up Go 1.16
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: 1.16

  #     - name: Check out code into the Go module directory
  #       uses: actions/checkout@v2

  #     - name: Run tests
  #       run: |
  #         PACKAGES=$(go list ./...)
  #         go test -v $PACKAGES

  # build:
  #   name: Build cheqd-node
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     - name: Set up Go 1.16
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: 1.16

  #     - name: Download and build starport
  #       run: curl https://get.starport.network/starport! | sudo bash

  #     - name: Check out code into the Go module directory
  #       uses: actions/checkout@v2

  #     - name: Starport build
  #       run: starport chain build

  # build-node-and-testnet-images:
  #   name: Build cheqd-node and testnet Docker images
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Check out
  #       uses: actions/checkout@v2

  #     - name: Build node image
  #       run: |
  #         docker build -f docker/cheqd_node/Dockerfile --no-cache -t cheqd-node .

  #     - name: Build testnet image
  #       run: |
  #         docker build -f docker/single_image_testnet/Dockerfile --no-cache -t cheqd-testnet .

  install-deb-package-and-set-up-pool:
    name: Install deb package and set up Docker pool
    runs-on: ubuntu-20.04 # exact version, not latest
    # needs: build-node-and-testnet-images
    steps:
      - name: Download and install deb package
        run: |
          wget https://github.com/cheqd/cheqd-node/releases/download/v0.2.1/cheqd-node_0.2.1_amd64.deb > /dev/null
          sudo dpkg -i cheqd-node_0.2.1_amd64.deb
          cheqd-noded help

      - name: Check out
        uses: actions/checkout@v2

      - name: Build node image
        run: |
          docker build -f docker/cheqd_node/Dockerfile --no-cache -t cheqd-node .

      - name: Set up 4 node docker pool
        run: |
          cd test/networks/docker_compose
          ./gen_node_configs.sh
          ./run_docker.sh > /dev/null &
          sleep 90
          docker ps

      - name: Add deb node as observer
        run: |
          cd && mkdir node5 && cd node5
          pwd
          cheqd-noded init node5 --home .
          cp ${{ env.NODE_CONFIGS_BASE }}/node0/.cheqdnode/config/genesis.json config/
          PEER0=$(cat ${{ env.NODE_CONFIGS_BASE }}/node0/node_id.txt)@$(docker inspect -f {{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}} docker_compose_node0_1):26656
          echo $PEER0
          sed -ri "s|persistent_peers = \".*\"|persistent_peers = \"${PEER0}\"|" config/config.toml
          sed -ri "s|laddr = \"tcp://127.0.0.1:26657\"|laddr = \"tcp://127.0.0.1:26677\"|" config/config.toml
          sed -ri "s|laddr = \"tcp://0.0.0.0:26656\"|laddr = \"tcp://0.0.0.0:26676\"|" config/config.toml
          cat config/config.toml
          cheqd-noded start --home . > /dev/null &
          sleep 90

      - name: Promote deb node to validator
        run: |
          docker ps
          sudo chown -R runner:docker ${{ env.NODE_CONFIGS_BASE }}
          rm -rf /home/runner/.cheqdnode
          cp -a ~/work/cheqd-node/cheqd-node/test/networks/docker_compose/node_configs/client/.cheqdnode/. /home/runner/.cheqdnode/
          cheqd-noded keys add node5-operator
          cheqd-noded keys list
          OP5_ADDRESS=$(cheqd-noded keys list | sed -nr 's/.*address: (.*?).*/\1/p' | sed -n 1p)
          echo $OP5_ADDRESS
          OP0_ADDRESS=$(cheqd-noded keys list | sed -nr 's/.*address: (.*?).*/\1/p' | sed -n 2p)
          echo $OP0_ADDRESS
          OP5_PUBKEY=$(cheqd-noded keys list | sed -nr 's/.*"key":"(.*?)".*/\1/p' | sed -n 1p)
          echo $OP5_PUBKEY
          NODE5_PUBKEY=$(cheqd-noded tendermint show-validator --home /home/runner/node5 | sed 's/\r//g')
          echo $NODE5_PUBKEY
          cheqd-noded tx bank send $OP0_ADDRESS $OP5_ADDRESS 1000000000000000ncheq --chain-id cheqd --fees 5000000ncheq --node http://$(docker inspect -f {{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}} docker_compose_node0_1):26657 -y
